// Supabase Configuration
// This file is auto-generated from .env file
// Do not edit this file directly - edit .env instead

const SUPABASE_URL = 'https://vwbrvxkzjwpppagkpipf.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3YnJ2eGt6andwcHBhZ2twaXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyMDEwNjksImV4cCI6MjA3OTc3NzA2OX0.nIeKbG2slPtm-W9r08Ohdr8FSNnb0OzhnZdLfh8IlGI';

// Initialize Supabase client
if (typeof supabase !== 'undefined') {
    const { createClient } = supabase;
    window.supabaseClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
} else {
    console.error('Supabase library not loaded. Make sure @supabase/supabase-js is loaded before this script.');
}
