// Supabase Configuration
// This file is auto-generated from .env file
// Do not edit this file directly - edit .env instead

const SUPABASE_URL = 'https://vwbrvxkzjwpppagkpipf.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3YnJ2eGt6andwcHBhZ2twaXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyMDEwNjksImV4cCI6MjA3OTc3NzA2OX0.nIeKbG2slPtm-W9r08Ohdr8FSNnb0OzhnZdLfh8IlGI';

// Initialize Supabase client - wait for library to load
(function initSupabase() {
    // The CDN version exposes supabase as a global
    // Try multiple ways to access it
    let createClientFn = null;
    
    // Method 1: Direct global supabase
    if (typeof supabase !== 'undefined') {
        if (typeof supabase.createClient === 'function') {
            createClientFn = supabase.createClient;
        } else if (supabase.default && typeof supabase.default.createClient === 'function') {
            createClientFn = supabase.default.createClient;
        }
    }
    
    // Method 2: window.supabase
    if (!createClientFn && typeof window !== 'undefined' && window.supabase) {
        if (typeof window.supabase.createClient === 'function') {
            createClientFn = window.supabase.createClient;
        } else if (window.supabase.default && typeof window.supabase.default.createClient === 'function') {
            createClientFn = window.supabase.default.createClient;
        }
    }
    
    if (createClientFn) {
        try {
            window.supabaseClient = createClientFn(SUPABASE_URL, SUPABASE_ANON_KEY);
            
            // Re-initialize database manager if it exists but doesn't have supabase
            if (window.dbManager && !window.dbManager.supabase) {
                window.dbManager.supabase = window.supabaseClient;
            }
            
            // Trigger a custom event so other scripts know Supabase is ready
            if (typeof window !== 'undefined' && window.dispatchEvent) {
                window.dispatchEvent(new CustomEvent('supabaseReady'));
            }
        } catch (error) {
            console.error('Error initializing Supabase client:', error);
            setTimeout(initSupabase, 100);
        }
    } else {
        // Retry after a short delay (max 50 times = 5 seconds)
        if (typeof initSupabase.retries === 'undefined') {
            initSupabase.retries = 0;
        }
        initSupabase.retries++;
        
        if (initSupabase.retries < 50) {
            setTimeout(initSupabase, 100);
        } else {
            console.error('Supabase library failed to load after 5 seconds. Check if the CDN script is loaded correctly.');
        }
    }
})();
