// Build script to generate supabase-config.js from .env file
const fs = require('fs');
const path = require('path');
require('dotenv').config();

const SUPABASE_URL = process.env.SUPABASE_URL || 'YOUR_SUPABASE_URL';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY';

// Check if we have valid values
if (SUPABASE_URL === 'YOUR_SUPABASE_URL' || SUPABASE_ANON_KEY === 'YOUR_SUPABASE_ANON_KEY') {
    console.warn('⚠️  Warning: Using placeholder values for Supabase configuration.');
    console.warn('   Make sure to set SUPABASE_URL and SUPABASE_ANON_KEY environment variables.');
    console.warn('   In Vercel: Go to Project Settings > Environment Variables');
}

const configContent = `// Supabase Configuration
// This file is auto-generated from .env file
// Do not edit this file directly - edit .env instead

const SUPABASE_URL = '${SUPABASE_URL}';
const SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';

// Initialize Supabase client
if (typeof supabase !== 'undefined') {
    const { createClient } = supabase;
    window.supabaseClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
} else {
    console.error('Supabase library not loaded. Make sure @supabase/supabase-js is loaded before this script.');
}
`;

const outputPath = path.join(__dirname, '..', 'js', 'supabase-config.js');

try {
    fs.writeFileSync(outputPath, configContent, 'utf8');
    console.log('✅ supabase-config.js successfully generated from .env');
    console.log(`   SUPABASE_URL: ${SUPABASE_URL.substring(0, 30)}...`);
} catch (error) {
    console.error('❌ Error generating supabase-config.js:', error.message);
    process.exit(1);
}

